FROM python

WORKDIR /app

COPY . /app

CMD ["python", "rng.py"]

# run `docker run -it` to run interactively (-i input + -t terminal)
# run `docker start -i` to start interactively (required the `run` to have been done with -t at least)